repository: jiangmuran/JMR-Navi
repository_url: https://github.com/jiangmuran/JMR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 洁面乳导航 · JMR-Navi
alias_en: JMR-Navi
alias_cn: 导航洁面乳
description: A Navigation Website for JMR
keywords: 洁面乳导航, JMR-Navi, JMR, Navi, Navigation, jiangmuran
url: https://byr-navi.com
established_at: "2016-10-01T00:00+08:00"

author: JMR
author_url: https://jiangmuran.com
organization: JMR
organization_url: https://jiangmuran.com
contact: jmr[at]jiangmuran[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
