name: build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      run: |
        sudo apt-get install ruby-full build-essential zlib1g-dev
      
        echo '# Install Ruby Gems to ~/gems'
        export GEM_HOME="$HOME/gems"
        export PATH="$HOME/gems/bin:$PATH"
        gem install jekyll bundler
        bundle install
        echo done1
        bundle exec jekyll build
        ls ./_site
        zip -r rel.zip ./_siter
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        name: Release 1.0.0
        body: New Release.
        draft: false
        prerelease: false
        files: rel.zip
