name: build
on:
  push:
    branches:
      - master2
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      run: 
        echo 114
